---
# Verify this with: http://lint.travis-ci.org/
language: ruby
# Delete dependency locks for matrix builds.
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
env:
  matrix:
    - PUPPET_VERSION="~> 3.8.5"
    - PUPPET_VERSION="~> 4.3.2"
matrix:
  exclude:
    - rvm: 2.2.0
      env: PUPPET_VERSION="~> 3.8.5"
# Only notify for failed builds.
notifications:
  email:
    on_success: never
