name          'gdsoperations-rbenv'
version       '0.0.5'
source        'https://github.com/gds-operations/puppet-rbenv'
author        'Government Digital Service'
license       'MIT'
summary       'System wide rbenv'
project_page  'https://github.com/gds-operations/puppet-rbenv'
