name          'gdsoperations-rbenv'
version       '1.2.0'
source        'https://github.com/gds-operations/puppet-rbenv'
author        'Government Digital Service'
license       'MIT'
summary       'System wide rbenv'
project_page  'https://github.com/gds-operations/puppet-rbenv'
